

#define USB_DEVICE_ONLY			1
#define USE_STATIC_OPTIONS              (USB_DEVICE_OPT_FULLSPEED | USB_OPT_REG_ENABLED | USB_OPT_AUTO_PLL)
#define FIXED_NUM_CONFIGURATIONS	1
#define DEVICE_STATE_AS_GPIOR		2
#define NO_DEVICE_REMOTE_WAKEUP		1
#define NO_DEVICE_SELF_POWER		1
#define INTERRUPT_CONTROL_ENDPOINT	1
